title: File

columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          alt:
            label: Description
            type: text
            width: 1/2
          class:
            type: text
            label: Class
            width: 1/2
