title: Text
icon: 📝

fields:
  headline:
    label: 💬 Content
    type: headline

  text:
    type: blocks
    width: 3/4
    fieldsets:
      - heading
      - text
      - list
      - markdown

  seo: sections/seo
