title: Site

columns:
  - width: 1/2
    sections:
      fields:
        type: fields
        fields:
          headline:
            label: Pages & Files
            type: headline
      pages:
        type: pages
        template:
          - home
          - default
          - error

      files:
        headline: Files
        type: files
        template: list

  - width: 1/2
    sections:
      seo:
        type: fields
        fields:
          seo: sections/seo
      cookie:
        type: fields
        fields:
          cookie: sections/cookie
