title: Site

columns:
  - width: 1
    sections:
      fields:
        type: fields
        fields:
          headline:
            label: 📰 Pages
            type: headline
      pages:
        type: pages
        template:
          - home
          - default
        image: icon
        layout: cards
        size: tiny

  - width: 1
    sections:
      seo:
        type: fields
        fields:
          seo: sections/seo
