name: Build & Deploy

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install composer dependencies
      
      - name: Install dependencies
        run: composer install

      # Install npm dependencies & build

      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build

      # FTP Deploy

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.ftp_path }}
